version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: aws_scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: aws_scripts/clean_up.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: aws_scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: aws_scripts/start_server.sh
      timeout: 300
      runas: ec2-user
